"""Store how many pages a document has

Revision ID: e77617cf54a5
Revises: f97c47e61c92
Create Date: 2026-09-13 01:51:43.166676
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e77617cf54a5'
down_revision: str | None = 'f97c47e61c92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('page_count')

    # ### end Alembic commands ###
