"""Keep the text read off a document

Revision ID: f7b30c63316b
Revises: e9d8c7e032dc
Create Date: 2026-09-12 17:10:21.482226
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f7b30c63316b'
down_revision: str | None = 'e9d8c7e032dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    # ### end Alembic commands ###
