"""Departments, assignment and decision history

Adds the department a user and a document belong to, the officer responsible for
a document, and the decision history that lets a head of department supersede a
decision without editing it.

The three new columns are NOT NULL, so this migration backfills before adding
the constraint: existing rows are placed in a department created here, and every
document is assigned to whoever uploaded it. Autogenerate cannot know any of
that, which is why the upgrade below is written by hand.

Revision ID: f97c47e61c92
Revises: f7b30c63316b
Create Date: 2026-09-13 01:37:57.408877
"""

from collections.abc import Sequence
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
import app.models.types

revision: str = 'f97c47e61c92'
down_revision: str | None = 'f7b30c63316b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('decided_as', sa.Text(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='decision_value', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('override_note', sa.Text(), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_decisions_decided_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_decisions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['decisions.id'], name=op.f('fk_decisions_superseded_by_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_document_id'), ['document_id'], unique=False)

    # A home for rows that predate departments. Created before the columns that
    # reference it, and only if the table is not already populated.
    departments = sa.table(
        "departments",
        sa.column("id", sa.Integer),
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("created_at", sa.DateTime),
    )
    connection = op.get_bind()
    existing = connection.execute(sa.text("SELECT count(*) FROM departments")).scalar()
    if not existing:
        op.bulk_insert(
            departments,
            [{
                "id": 1,
                "code": "GEN",
                "name": "General Office",
                "created_at": datetime(2026, 1, 1, tzinfo=timezone.utc).replace(tzinfo=None),
            }],
        )

    with op.batch_alter_table('documents', schema=None) as batch_op:
        # Added nullable, backfilled below, then tightened.
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_documents_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_documents_assigned_to_users'), 'users', ['assigned_to'], ['id'])

    # Existing documents belong to the general office and stay with whoever
    # uploaded them.
    connection.execute(sa.text("UPDATE documents SET department_id = 1 WHERE department_id IS NULL"))
    connection.execute(sa.text("UPDATE documents SET assigned_to = uploaded_by WHERE assigned_to IS NULL"))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('box_left', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('box_top', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('box_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('box_height', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_created_by_users'), 'users', ['created_by'], ['id'])

    connection.execute(sa.text("UPDATE users SET department_id = 1 WHERE department_id IS NULL"))

    # Now that every row has a value, make the three columns required. Done last
    # so that a half-applied migration cannot leave a NOT NULL column empty.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department_id', existing_type=sa.Integer(), nullable=False)
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('department_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('assigned_to', existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_created_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_department_id_departments'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_column('created_by')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('box_height')
        batch_op.drop_column('box_width')
        batch_op.drop_column('box_top')
        batch_op.drop_column('box_left')
        batch_op.drop_column('page_number')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_assigned_to_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_documents_department_id_departments'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_department_id'))
        batch_op.drop_index(batch_op.f('ix_documents_assigned_to'))
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_document_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_created_at'))

    op.drop_table('decisions')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
